// <auto-generated />
using System;
using DuneWarLastFantasy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuneWarLastFantasy.Migrations
{
    [DbContext(typeof(AppContextPostgree))]
    partial class AppContextPostgreeModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuneWarLastFantasy.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Uid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticlesId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Uid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticlesId");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Record")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.other.Arsenal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumCannon")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Arsenal", "DuneWar");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.other.Factory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Factory", "DuneWar");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.other.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ArsenalID")
                        .HasColumnType("integer")
                        .HasColumnName("ArsenalID");

                    b.Property<int>("FactorioID")
                        .HasColumnType("integer")
                        .HasColumnName("FactorioID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ArsenalID");

                    b.HasIndex("FactorioID");

                    b.ToTable("Product", "DuneWar");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.Author", b =>
                {
                    b.HasOne("DuneWarLastFantasy.Models.Article", "Articles")
                        .WithMany("Authors")
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articles");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.other.Product", b =>
                {
                    b.HasOne("DuneWarLastFantasy.Models.other.Arsenal", "Arsenal")
                        .WithMany("Products")
                        .HasForeignKey("ArsenalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuneWarLastFantasy.Models.other.Factory", "Factorio")
                        .WithMany("Products")
                        .HasForeignKey("FactorioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arsenal");

                    b.Navigation("Factorio");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.Article", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.other.Arsenal", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DuneWarLastFantasy.Models.other.Factory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
